# Hugging Face Spaces configuration for AgreeUpon Legal Assistant
# See: https://huggingface.co/docs/hub/spaces-config-reference

title: AgreeUpon Legal Assistant
sdk: docker
license: mit
emoji: "🚀"
colorFrom: blue
colorTo: green
app_port: 8000
